In [1]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 


In [24]:
data = pd.read_csv("carona.csv")

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131 entries, 0 to 130
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   fiver         131 non-null    int64  
 1   breath        131 non-null    int64  
 2   coughing      131 non-null    int64  
 3   cold          131 non-null    int64  
 4   discomfort    131 non-null    int64  
 5   age           131 non-null    int64  
 6   sex           131 non-null    int64  
 7   infectionper  131 non-null    int64  
 8   Unnamed: 8    0 non-null      float64
dtypes: float64(1), int64(8)
memory usage: 9.3 KB


In [26]:
data.head()

fiver  breath  coughing  cold  discomfort  age  sex  infectionper  \
0      1       1         1     1           1   60    1             1   
1      1       1         1     0           1   30    1             1   
2      1       1         0     0           1   60    1             1   
3      1       1         0     1           1   40    1             1   
4      1       1         0     0           1   52    0             1   

   Unnamed: 8  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN

In [27]:
data.keys()

Index(['fiver', 'breath', 'coughing', 'cold', 'discomfort', 'age', 'sex',
       'infectionper', 'Unnamed: 8'],
      dtype='object')

In [28]:
data = data[['fiver', 'breath', 'coughing', 'cold', 'discomfort', 'age', 'sex',
       'infectionper']]

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131 entries, 0 to 130
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   fiver         131 non-null    int64
 1   breath        131 non-null    int64
 2   coughing      131 non-null    int64
 3   cold          131 non-null    int64
 4   discomfort    131 non-null    int64
 5   age           131 non-null    int64
 6   sex           131 non-null    int64
 7   infectionper  131 non-null    int64
dtypes: int64(8)
memory usage: 8.2 KB


In [30]:
np.random.seed(42)
shuffled = np.random.permutation(len(data))

In [36]:
shuffled

array([ 55,  40,  19,  31, 115,  56,  69, 105,  81,  26,  95,  27,  64,
         4,  97, 100,  36,  80,  93,  84,  18,  10, 122,  11, 127,  45,
        70,  78,  47,   0,  12,  42,  51,  24,  67, 113,  89,  15,  77,
        22,  44,  65,  96,  30,  62, 125,   9,  33,  66,  25, 118,  28,
        98, 129,  53,   5,  68,  73,  39,  49,  35,  16, 126,  34,  85,
         7,  43,  76, 104, 110,   8,  13,  94,   3,  17,  38,  72, 101,
         6,  83, 112, 114,  54,  50, 120,  46, 108,  61, 128,  79, 123,
        91,  41,  58,  90,  48,  88, 111,  57,  75,  32, 124,  59,  63,
       109,  37,  29, 107, 117,   1,  52,  21,   2,  23, 103,  99, 116,
        87, 119,  74,  86,  82, 121, 130,  20,  60,  71, 106,  14,  92,
       102])

In [10]:
X = np.asarray(data[['fiver','breath','coughing', 'cold', 'discomfort', 'age', 'sex']])

In [11]:
X[1:12]

array([[ 1,  1,  1,  0,  1, 30,  1],
       [ 1,  1,  0,  0,  1, 60,  1],
       [ 1,  1,  0,  1,  1, 40,  1],
       [ 1,  1,  0,  0,  1, 52,  0],
       [ 0,  1,  1,  0,  1, 65,  0],
       [ 0,  1,  1,  0,  1, 45,  1],
       [ 1,  1,  1,  0,  1, 78,  0],
       [ 0,  1,  0,  0,  1, 57,  1],
       [ 1,  1,  0,  1,  1, 55,  0],
       [ 1,  0,  0,  0,  1, 60,  1],
       [ 1,  1,  0,  0,  1, 84,  1]], dtype=int64)

In [12]:
y = np.asarray(data[['infectionper']])

In [13]:
y[1:12]

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=int64)

In [14]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)

In [15]:
X[1:12]

array([[ 1.03892496,  0.96253342,  0.77302068, -0.74801324,  1.03892496,
        -0.95198305,  0.6990253 ],
       [ 1.03892496,  0.96253342, -1.29362645, -0.74801324,  1.03892496,
         0.27951576,  0.6990253 ],
       [ 1.03892496,  0.96253342, -1.29362645,  1.33687473,  1.03892496,
        -0.54148344,  0.6990253 ],
       [ 1.03892496,  0.96253342, -1.29362645, -0.74801324,  1.03892496,
        -0.04888392, -1.4305634 ],
       [-0.96253342,  0.96253342,  0.77302068, -0.74801324,  1.03892496,
         0.48476556, -1.4305634 ],
       [-0.96253342,  0.96253342,  0.77302068, -0.74801324,  1.03892496,
        -0.33623364,  0.6990253 ],
       [ 1.03892496,  0.96253342,  0.77302068, -0.74801324,  1.03892496,
         1.01841504, -1.4305634 ],
       [-0.96253342,  0.96253342, -1.29362645, -0.74801324,  1.03892496,
         0.15636588,  0.6990253 ],
       [ 1.03892496,  0.96253342, -1.29362645,  1.33687473,  1.03892496,
         0.07426596, -1.4305634 ],
       [ 1.03892496, -1.0389

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (104, 7) (104, 1)
Test set: (27, 7) (27, 1)


In [17]:
from sklearn.linear_model import LogisticRegression
